// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "b14119f8-049c-4853-af4f-ab187c05a1a8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFirinChange();
void onIsitmaChange();
void onKapiChange();
void onSicaklikChange();
void onSogutmaChange();

CloudLight firin;
CloudLight isitma;
CloudLight kapi;
CloudLight sicaklik;
CloudLight sogutma;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(firin, READWRITE, ON_CHANGE, onFirinChange);
  ArduinoCloud.addProperty(isitma, READWRITE, ON_CHANGE, onIsitmaChange);
  ArduinoCloud.addProperty(kapi, READWRITE, ON_CHANGE, onKapiChange);
  ArduinoCloud.addProperty(sicaklik, READWRITE, ON_CHANGE, onSicaklikChange);
  ArduinoCloud.addProperty(sogutma, READWRITE, ON_CHANGE, onSogutmaChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
